services:
  redis:
    image: redis:8
    container_name: redis

  api:
    build:
      context: ./api
    container_name: campsite-api
    env_file:
      - ./api/.env
    command: ["pnpm", "dev"]
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - redis
  
  worker:
    build:
      context: ./api
    container_name: campsite-worker
    env_file:
      - ./api/.env
    command: ["pnpm", "worker:dev"]
    depends_on:
      - redis

  postgres:
    image: postgres:17
    container_name: keycloak-postgres
    env_file:
      - .env
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    env_file:
      - .env
    depends_on:
      - postgres
  
  nginx:
    image: nginx:1.27
    ports:
      - "8081:80"
      #- "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - keycloak

  client:
    build:
      context: ./client
    container_name: campsite-client
    env_file:
      - ./client/.env.local
    command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/vite.config.js:/app/vite.config.js
      - ./client/tsconfig.json:/app/tsconfig.json
    depends_on:
      - api

volumes:
  keycloak_postgres_data: