services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: campsite-api
    env_file:
      - .env
    command: ["pnpm", "dev"]
    ports:
      - "3000:3000"
    depends_on:
      - redis
  
  worker:
    build: .
    container_name: campsite-worker
    env_file:
      - .env
    command: ["pnpm", "worker:dev"]
    depends_on:
      - redis