services:
  redis:
    image: redis:8.01-alpine
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: campsite-api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - redis