services:
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
    container_name: campsite-api
    env_file:
      - ./api/.env
    command: ["pnpm", "dev"]
    ports:
      - "3101:3101"
    depends_on:
      - redis
  
  worker:
    build:
      context: ./api
    container_name: campsite-worker
    env_file:
      - ./api/.env
    command: ["pnpm", "worker:dev"]
    depends_on:
      - redis

  postgres:
    image: postgres:17
    container_name: keycloak-postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.2
    container_name: keycloak
    command: start-dev
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  
  client:
   build:
     context: ./client
   container_name: campsite-client
   env_file:
     - ./client/.env
   command: ["pnpm", "dev", "--host", "0.0.0.0", "--port", "3000"]
   ports:
     - "3000:3000"
   depends_on:
     - api

volumes:
  keycloak_postgres_data: